const initialState = {
  January: {
    "01": { weekday: "Friday", events: [] },
    "02": { weekday: "Saturday", events: [] },
    "03": { weekday: "Sunday", events: [] },
    "04": { weekday: "Monday", events: [] },
    "05": { weekday: "Tuesday", events: [] },
    "06": { weekday: "Wednesday", events: [] },
    "07": { weekday: "Thursday", events: [] },
    "08": { weekday: "Friday", events: [] },
    "09": { weekday: "Saturday", events: [] },
    10: { weekday: "Sunday", events: [] },
    11: { weekday: "Monday", events: [] },
    12: { weekday: "Tuesday", events: [] },
    13: { weekday: "Wednesday", events: [] },
    14: { weekday: "Thursday", events: [] },
    15: { weekday: "Friday", events: [] },
    16: { weekday: "Saturday", events: [] },
    17: { weekday: "Sunday", events: [] },
    18: { weekday: "Monday", events: [] },
    19: { weekday: "Tuesday", events: [] },
    20: { weekday: "Wednesday", events: [] },
    21: { weekday: "Thursday", events: [] },
    22: { weekday: "Friday", events: [] },
    23: { weekday: "Saturday", events: [] },
    24: { weekday: "Sunday", events: [] },
    25: { weekday: "Monday", events: [] },
    26: { weekday: "Tuesday", events: [] },
    27: { weekday: "Wednesday", events: [] },
    28: { weekday: "Thursday", events: [] },
    29: { weekday: "Friday", events: [] },
    30: { weekday: "Saturday", events: [] },
    31: { weekday: "Sunday", events: [] },
  },
  February: {
    "01": { weekday: "Monday", events: [] },
    "02": { weekday: "Tuesday", events: [] },
    "03": { weekday: "Wednesday", events: [] },
    "04": { weekday: "Thursday", events: [] },
    "05": { weekday: "Friday", events: [] },
    "06": { weekday: "Saturday", events: [] },
    "07": { weekday: "Sunday", events: [] },
    "08": { weekday: "Monday", events: [] },
    "09": { weekday: "Tuesday", events: [] },
    10: { weekday: "Wednesday", events: [] },
    11: { weekday: "Thursday", events: [] },
    12: { weekday: "Friday", events: [] },
    13: { weekday: "Saturday", events: [] },
    14: { weekday: "Sunday", events: [] },
    15: { weekday: "Monday", events: [] },
    16: { weekday: "Tuesday", events: [] },
    17: { weekday: "Wednesday", events: [] },
    18: { weekday: "Thursday", events: [] },
    19: { weekday: "Friday", events: [] },
    20: { weekday: "Saturday", events: [] },
    21: { weekday: "Sunday", events: [] },
    22: { weekday: "Monday", events: [] },
    23: { weekday: "Tuesday", events: [] },
    24: { weekday: "Wednesday", events: [] },
    25: { weekday: "Thursday", events: [] },
    26: { weekday: "Friday", events: [] },
    27: { weekday: "Saturday", events: [] },
    28: { weekday: "Sunday", events: [] },
  },
  March: {
    "01": { weekday: "Monday", events: [] },
    "02": { weekday: "Tuesday", events: [] },
    "03": { weekday: "Wednesday", events: [] },
    "04": { weekday: "Thursday", events: [] },
    "05": { weekday: "Friday", events: [] },
    "06": { weekday: "Saturday", events: [] },
    "07": { weekday: "Sunday", events: [] },
    "08": { weekday: "Monday", events: [] },
    "09": { weekday: "Tuesday", events: [] },
    10: { weekday: "Wednesday", events: [] },
    11: { weekday: "Thursday", events: [] },
    12: { weekday: "Friday", events: [] },
    13: { weekday: "Saturday", events: [] },
    14: { weekday: "Sunday", events: [] },
    15: { weekday: "Monday", events: [] },
    16: { weekday: "Tuesday", events: [] },
    17: { weekday: "Wednesday", events: [] },
    18: { weekday: "Thursday", events: [] },
    19: { weekday: "Friday", events: [] },
    20: { weekday: "Saturday", events: [] },
    21: { weekday: "Sunday", events: [] },
    22: { weekday: "Monday", events: [] },
    23: { weekday: "Tuesday", events: [] },
    24: { weekday: "Wednesday", events: [] },
    25: { weekday: "Thursday", events: [] },
    26: { weekday: "Friday", events: [] },
    27: { weekday: "Saturday", events: [] },
    28: { weekday: "Sunday", events: [] },
    29: { weekday: "Monday", events: [] },
    30: { weekday: "Tuesday", events: [] },
    31: { weekday: "Wednesday", events: [] },
  },
  April: {
    "01": { weekday: "Thursday", events: [] },
    "02": { weekday: "Friday", events: [] },
    "03": { weekday: "Saturday", events: [] },
    "04": { weekday: "Sunday", events: [] },
    "05": { weekday: "Monday", events: [] },
    "06": { weekday: "Tuesday", events: [] },
    "07": { weekday: "Wednesday", events: [] },
    "08": { weekday: "Thursday", events: [] },
    "09": { weekday: "Friday", events: [] },
    10: { weekday: "Saturday", events: [] },
    11: { weekday: "Sunday", events: [] },
    12: { weekday: "Monday", events: [] },
    13: { weekday: "Tuesday", events: [] },
    14: { weekday: "Wednesday", events: [] },
    15: { weekday: "Thursday", events: [] },
    16: { weekday: "Friday", events: [] },
    17: { weekday: "Saturday", events: [] },
    18: { weekday: "Sunday", events: [] },
    19: { weekday: "Monday", events: [] },
    20: { weekday: "Tuesday", events: [] },
    21: { weekday: "Wednesday", events: [] },
    22: { weekday: "Thursday", events: [] },
    23: { weekday: "Friday", events: [] },
    24: { weekday: "Saturday", events: [] },
    25: { weekday: "Sunday", events: [] },
    26: { weekday: "Monday", events: [] },
    27: { weekday: "Tuesday", events: [] },
    28: { weekday: "Wednesday", events: [] },
    29: { weekday: "Thursday", events: [] },
    30: { weekday: "Friday", events: [] },
  },
  May: {
    "01": { weekday: "Saturday", events: [] },
    "02": { weekday: "Sunday", events: [] },
    "03": { weekday: "Monday", events: [] },
    "04": { weekday: "Tuesday", events: [] },
    "05": { weekday: "Wednesday", events: [] },
    "06": { weekday: "Thursday", events: [] },
    "07": { weekday: "Friday", events: [] },
    "08": { weekday: "Saturday", events: [] },
    "09": { weekday: "Sunday", events: [] },
    10: { weekday: "Monday", events: [] },
    11: { weekday: "Tuesday", events: [] },
    12: { weekday: "Wednesday", events: [] },
    13: { weekday: "Thursday", events: [] },
    14: { weekday: "Friday", events: [] },
    15: { weekday: "Saturday", events: [] },
    16: { weekday: "Sunday", events: [] },
    17: { weekday: "Monday", events: [] },
    18: { weekday: "Tuesday", events: [] },
    19: { weekday: "Wednesday", events: [] },
    20: { weekday: "Thursday", events: [] },
    21: { weekday: "Friday", events: [] },
    22: { weekday: "Saturday", events: [] },
    23: { weekday: "Sunday", events: [] },
    24: { weekday: "Monday", events: [] },
    25: { weekday: "Tuesday", events: [] },
    26: { weekday: "Wednesday", events: [] },
    27: { weekday: "Thursday", events: [] },
    28: { weekday: "Friday", events: [] },
    29: { weekday: "Saturday", events: [] },
    30: { weekday: "Sunday", events: [] },
    31: { weekday: "Monday", events: [] },
  },
  June: {
    "01": { weekday: "Tuesday", events: [] },
    "02": { weekday: "Wednesday", events: [] },
    "03": { weekday: "Thursday", events: [] },
    "04": { weekday: "Friday", events: [] },
    "05": { weekday: "Saturday", events: [] },
    "06": { weekday: "Sunday", events: [] },
    "07": { weekday: "Monday", events: [] },
    "08": { weekday: "Tuesday", events: [] },
    "09": { weekday: "Wednesday", events: [] },
    10: { weekday: "Thursday", events: [] },
    11: { weekday: "Friday", events: [] },
    12: { weekday: "Saturday", events: [] },
    13: { weekday: "Sunday", events: [] },
    14: { weekday: "Monday", events: [] },
    15: { weekday: "Tuesday", events: [] },
    16: { weekday: "Wednesday", events: [] },
    17: { weekday: "Thursday", events: [] },
    18: { weekday: "Friday", events: [] },
    19: { weekday: "Saturday", events: [] },
    20: { weekday: "Sunday", events: [] },
    21: { weekday: "Monday", events: [] },
    22: { weekday: "Tuesday", events: [] },
    23: { weekday: "Wednesday", events: [] },
    24: { weekday: "Thursday", events: [] },
    25: { weekday: "Friday", events: [] },
    26: { weekday: "Saturday", events: [] },
    27: { weekday: "Sunday", events: [] },
    28: { weekday: "Monday", events: [] },
    29: { weekday: "Tuesday", events: [] },
    30: { weekday: "Wednesday", events: [] },
  },
  July: {
    "01": { weekday: "Thursday", events: [] },
    "02": { weekday: "Friday", events: [] },
    "03": { weekday: "Saturday", events: [] },
    "04": { weekday: "Sunday", events: [] },
    "05": { weekday: "Monday", events: [] },
    "06": { weekday: "Tuesday", events: [] },
    "07": { weekday: "Wednesday", events: [] },
    "08": { weekday: "Thursday", events: [] },
    "09": { weekday: "Friday", events: [] },
    10: { weekday: "Saturday", events: [] },
    11: { weekday: "Sunday", events: [] },
    12: { weekday: "Monday", events: [] },
    13: { weekday: "Tuesday", events: [] },
    14: { weekday: "Wednesday", events: [] },
    15: { weekday: "Thursday", events: [] },
    16: { weekday: "Friday", events: [] },
    17: { weekday: "Saturday", events: [] },
    18: { weekday: "Sunday", events: [] },
    19: { weekday: "Monday", events: [] },
    20: { weekday: "Tuesday", events: [] },
    21: { weekday: "Wednesday", events: [] },
    22: { weekday: "Thursday", events: [] },
    23: { weekday: "Friday", events: [] },
    24: { weekday: "Saturday", events: [] },
    25: { weekday: "Sunday", events: [] },
    26: { weekday: "Monday", events: [] },
    27: { weekday: "Tuesday", events: [] },
    28: { weekday: "Wednesday", events: [] },
    29: { weekday: "Thursday", events: [] },
    30: { weekday: "Friday", events: [] },
    31: { weekday: "Saturday", events: [] },
  },
  August: {
    "01": { weekday: "Sunday", events: [] },
    "02": { weekday: "Monday", events: [] },
    "03": { weekday: "Tuesday", events: [] },
    "04": { weekday: "Wednesday", events: [] },
    "05": { weekday: "Thursday", events: [] },
    "06": { weekday: "Friday", events: [] },
    "07": { weekday: "Saturday", events: [] },
    "08": { weekday: "Sunday", events: [] },
    "09": { weekday: "Monday", events: [] },
    10: { weekday: "Tuesday", events: [] },
    11: { weekday: "Wednesday", events: [] },
    12: { weekday: "Thursday", events: [] },
    13: { weekday: "Friday", events: [] },
    14: { weekday: "Saturday", events: [] },
    15: { weekday: "Sunday", events: [] },
    16: { weekday: "Monday", events: [] },
    17: { weekday: "Tuesday", events: [] },
    18: { weekday: "Wednesday", events: [] },
    19: { weekday: "Thursday", events: [] },
    20: { weekday: "Friday", events: [] },
    21: { weekday: "Saturday", events: [] },
    22: { weekday: "Sunday", events: [] },
    23: { weekday: "Monday", events: [] },
    24: { weekday: "Tuesday", events: [] },
    25: { weekday: "Wednesday", events: [] },
    26: { weekday: "Thursday", events: [] },
    27: { weekday: "Friday", events: [] },
    28: { weekday: "Saturday", events: [] },
    29: { weekday: "Sunday", events: [] },
    30: { weekday: "Monday", events: [] },
    31: { weekday: "Tuesday", events: [] },
  },
  September: {
    "01": { weekday: "Wednesday", events: [] },
    "02": { weekday: "Thursday", events: [] },
    "03": { weekday: "Friday", events: [] },
    "04": { weekday: "Saturday", events: [] },
    "05": { weekday: "Sunday", events: [] },
    "06": { weekday: "Monday", events: [] },
    "07": { weekday: "Tuesday", events: [] },
    "08": { weekday: "Wednesday", events: [] },
    "09": { weekday: "Thursday", events: [] },
    10: { weekday: "Friday", events: [] },
    11: { weekday: "Saturday", events: [] },
    12: { weekday: "Sunday", events: [] },
    13: { weekday: "Monday", events: [] },
    14: { weekday: "Tuesday", events: [] },
    15: { weekday: "Wednesday", events: [] },
    16: { weekday: "Thursday", events: [] },
    17: { weekday: "Friday", events: [] },
    18: { weekday: "Saturday", events: [] },
    19: { weekday: "Sunday", events: [] },
    20: { weekday: "Monday", events: [] },
    21: { weekday: "Tuesday", events: [] },
    22: { weekday: "Wednesday", events: [] },
    23: { weekday: "Thursday", events: [] },
    24: { weekday: "Friday", events: [] },
    25: { weekday: "Saturday", events: [] },
    26: { weekday: "Sunday", events: [] },
    27: { weekday: "Monday", events: [] },
    28: { weekday: "Tuesday", events: [] },
    29: { weekday: "Wednesday", events: [] },
    30: { weekday: "Thursday", events: [] },
  },
  October: {
    "01": { weekday: "Friday", events: [] },
    "02": { weekday: "Saturday", events: [] },
    "03": { weekday: "Sunday", events: [] },
    "04": { weekday: "Monday", events: [] },
    "05": { weekday: "Tuesday", events: [] },
    "06": { weekday: "Wednesday", events: [] },
    "07": { weekday: "Thursday", events: [] },
    "08": { weekday: "Friday", events: [] },
    "09": { weekday: "Saturday", events: [] },
    10: { weekday: "Sunday", events: [] },
    11: { weekday: "Monday", events: [] },
    12: { weekday: "Tuesday", events: [] },
    13: { weekday: "Wednesday", events: [] },
    14: { weekday: "Thursday", events: [] },
    15: { weekday: "Friday", events: [] },
    16: { weekday: "Saturday", events: [] },
    17: { weekday: "Sunday", events: [] },
    18: { weekday: "Monday", events: [] },
    19: { weekday: "Tuesday", events: [] },
    20: { weekday: "Wednesday", events: [] },
    21: { weekday: "Thursday", events: [] },
    22: { weekday: "Friday", events: [] },
    23: { weekday: "Saturday", events: [] },
    24: { weekday: "Sunday", events: [] },
    25: { weekday: "Monday", events: [] },
    26: { weekday: "Tuesday", events: [] },
    27: { weekday: "Wednesday", events: [] },
    28: { weekday: "Thursday", events: [] },
    29: { weekday: "Friday", events: [] },
    30: { weekday: "Saturday", events: [] },
    31: { weekday: "Sunday", events: [] },
  },
  November: {
    "01": { weekday: "Monday", events: [] },
    "02": { weekday: "Tuesday", events: [] },
    "03": { weekday: "Wednesday", events: [] },
    "04": { weekday: "Thursday", events: [] },
    "05": { weekday: "Friday", events: [] },
    "06": { weekday: "Saturday", events: [] },
    "07": { weekday: "Sunday", events: [] },
    "08": { weekday: "Monday", events: [] },
    "09": { weekday: "Tuesday", events: [] },
    10: { weekday: "Wednesday", events: [] },
    11: { weekday: "Thursday", events: [] },
    12: { weekday: "Friday", events: [] },
    13: { weekday: "Saturday", events: [] },
    14: { weekday: "Sunday", events: [] },
    15: { weekday: "Monday", events: [] },
    16: { weekday: "Tuesday", events: [] },
    17: { weekday: "Wednesday", events: [] },
    18: { weekday: "Thursday", events: [] },
    19: { weekday: "Friday", events: [] },
    20: { weekday: "Saturday", events: [] },
    21: { weekday: "Sunday", events: [] },
    22: { weekday: "Monday", events: [] },
    23: { weekday: "Tuesday", events: [] },
    24: { weekday: "Wednesday", events: [] },
    25: { weekday: "Thursday", events: [] },
    26: { weekday: "Friday", events: [] },
    27: { weekday: "Saturday", events: [] },
    28: { weekday: "Sunday", events: [] },
    29: { weekday: "Monday", events: [] },
    30: { weekday: "Tuesday", events: [] },
  },
  December: {
    "01": { weekday: "Wednesday", events: [] },
    "02": { weekday: "Thursday", events: [] },
    "03": { weekday: "Friday", events: [] },
    "04": { weekday: "Saturday", events: [] },
    "05": { weekday: "Sunday", events: [] },
    "06": { weekday: "Monday", events: [] },
    "07": { weekday: "Tuesday", events: [] },
    "08": { weekday: "Wednesday", events: [] },
    "09": { weekday: "Thursday", events: [] },
    10: { weekday: "Friday", events: [] },
    11: { weekday: "Saturday", events: [] },
    12: { weekday: "Sunday", events: [] },
    13: { weekday: "Monday", events: [] },
    14: { weekday: "Tuesday", events: [] },
    15: { weekday: "Wednesday", events: [] },
    16: { weekday: "Thursday", events: [] },
    17: { weekday: "Friday", events: [] },
    18: { weekday: "Saturday", events: [] },
    19: { weekday: "Sunday", events: [] },
    20: { weekday: "Monday", events: [] },
    21: { weekday: "Tuesday", events: [] },
    22: { weekday: "Wednesday", events: [] },
    23: { weekday: "Thursday", events: [] },
    24: { weekday: "Friday", events: [] },
    25: { weekday: "Saturday", events: [] },
    26: { weekday: "Sunday", events: [] },
    27: { weekday: "Monday", events: [] },
    28: { weekday: "Tuesday", events: [] },
    29: { weekday: "Wednesday", events: [] },
    30: { weekday: "Thursday", events: [] },
    31: { weekday: "Friday", events: [] },
  },
};

/**
 * Schedule reducer for Redux. Controls the schedule state.
 * @param {Object} state
 * @param {function} action
 * @returns Object
 */

const scheduleReducer = (state = initialState, action) => {
  switch (action.type) {
    case "GET_SCHDULE":
      return state;
    case "CREATE_EVENT":
      return createNewEvent(state, action.payload);
    default:
      return state;
  }
};

export default scheduleReducer;

/**
 * Function that creates new event in the scheduler.
 * @param {Object} state
 * @param {Object} payload
 * @returns Object
 */

function createNewEvent(state, payload) {
  const eventName = payload.eventName;
  const [eventDate, eventTime] = payload.timeDate.split("T");
  const [eventYear, eventMonth, eventDay] = eventDate.split("-");
  const monthConverter = {
    "01": "January",
    "02": "February",
    "03": "March",
    "04": "April",
    "05": "May",
    "06": "June",
    "07": "July",
    "08": "August",
    "09": "September",
    10: "October",
    11: "November",
    12: "December",
  };
  const newState = state;

  newState[monthConverter[eventMonth]][eventDay].events.push({ eventName, eventTime });
  return newState;
}
